[package]
name = "mergebom-web"
version = "0.1.0"
edition = "2021"
authors = ["Daniele Basile <asterix24@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
async-std = { version = "1.8.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
regex = "1"
lazy_static = "1.2"
calamine = "0.18"
csv = "1.1"
serde_json = "1.0"
